name: ci-md
on:
  push:
    branches:
      - main
    paths:
      - '**.md'

  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    runs-on:
      - ubuntu-22.04

    steps:
      - name: Check out last commit on branch main
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      - name: Setup linter
        run: gem install mdl

      - name: Lint all Markdown files
        run: mdl .
